sudo: required
services: 
  - docker

before_install:
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project electric-eagle
  - gcloud config set compute/zone europe-west2-a
  - gcloud container clusters get-credentials cluster-1