sudo: required
services: 
  - docker

before_install:
  - openssl aes-256-cbc -K $encrypted_7e3b9f3f674f_key -iv $encrypted_7e3b9f3f674f_iv -in travis.json.enc -out travis.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file travis.json.enc
  - gcloud config set project electric-eagle
  - gcloud config set compute/zone europe-west2-a
  - gcloud container clusters get-credentials cluster-1
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t rathore287/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rathore287/react-test npm test 

deploy:
  provider: script
  script: bash ./deploy.sh

  on:
    branch: master