apiVersion: certmanager.k8s.io/v1alpha2
kind: Certificate
metadata:
  name: always-building-company
spec:
  secretName: always-building
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: alwaysbuilding.company
  dnsNames:
    - alwaysbuilding.company
    - www.alwaysbuilding.company
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - alwaysbuilding.company
          - www.alwaysbuilding.company
